name: jait_jait
description: Flutter project Jait Jait

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
#  sdk: ">=2.15.0 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  get_storage: ^2.0.3
  animations: ^2.0.2
  flutter_custom_clippers: ^2.0.0
  flutter_easyloading: ^3.0.3
  persistent_bottom_nav_bar: ^4.0.2
  bubble: ^1.2.1
  table_calendar: ^3.0.3
  flutter_rating_bar: ^4.0.0

  firebase_core: ^1.7.0
  flutter_chat_ui: ^1.5.4
  flutter_firebase_chat_core: ^1.5.2
  firebase_auth: ^3.3.5
  firebase_storage: ^10.2.5
  flutter_chat_types: ^3.2.2

  syncfusion_flutter_datepicker: ^19.4.42

  file_picker: ^4.3.2
  http: ^0.13.4
  image_picker: ^0.8.4+4
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2

flutter_native_splash:
  color: '#fde3f0'
  image: "assets/icon/logo_jaitjait.png"
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/img/
    - assets/img/avatars/
    - assets/img/articles/

